import type { Bindings } from "../types";
import { generateSoundEffect, inferCategory, promptToName } from "../lib/elevenlabs";

const SYSTEM_PROMPT = `You are ByteBeat's AI DJ — a music production assistant embedded in a browser-based MIDI pad controller.

The user has a 4x4 grid of 16 pads. Each pad can be assigned a sound generated by ElevenLabs.
You can see their current pad layout and BPM in the context.

Your job:
- Suggest what sounds would work well together
- Recommend prompts to generate new sounds via ElevenLabs
- Give production tips (BPM, patterns, genres)
- Be concise, creative, and hype about music

When suggesting a sound to generate, format it as:
GENERATE: <prompt text here>

Keep responses short (2-4 sentences max). You are a DJ, not a professor.`;

interface Pad {
  id: string;
  label: string;
  soundName: string | null;
  color: string;
}

export async function handleAgentSuggest(
  env: Bindings,
  message: string,
  context: { pads: Pad[]; bpm: number }
) {
  const assignedPads = context.pads.filter((p) => p.soundName);
  const contextSummary = `BPM: ${context.bpm}. Assigned pads: ${
    assignedPads.map((p) => `${p.label}: ${p.soundName}`).join(", ") || "none"
  }. Empty pads: ${context.pads.length - assignedPads.length}.`;

  const aiResult = await env.AI.run(
    "@cf/meta/llama-3.1-8b-instruct" as Parameters<typeof env.AI.run>[0],
    {
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: `${contextSummary}\n\nUser: ${message}` },
      ],
      max_tokens: 256,
    }
  );

  const reply =
    typeof aiResult === "object" && aiResult !== null && "response" in aiResult
      ? String((aiResult as { response: unknown }).response)
      : "Let's make some noise! Tell me what vibe you're going for.";

  const generateMatch = reply.match(/GENERATE:\s*(.+?)(?:\n|$)/i);
  let generatedSound = null;

  if (generateMatch?.[1] && env.ELEVENLABS_API_KEY) {
    const prompt = generateMatch[1].trim();
    try {
      const audioBytes = await generateSoundEffect(prompt, env.ELEVENLABS_API_KEY);
      const soundId = `agent_${crypto.randomUUID().slice(0, 8)}`;
      const r2Key = `sounds/${soundId}.mp3`;

      await env.AUDIO_BUCKET.put(r2Key, audioBytes, {
        httpMetadata: { contentType: "audio/mpeg" },
        customMetadata: { prompt, source: "agent" },
      });

      generatedSound = {
        id: soundId,
        name: promptToName(prompt),
        url: `/audio/${r2Key}`,
        prompt,
        category: inferCategory(prompt),
      };

      await env.AUDIO_CACHE.put(
        `sound:${btoa(prompt).slice(0, 32)}`,
        JSON.stringify(generatedSound),
        { expirationTtl: 86400 }
      );
    } catch {
      // Generation failed silently — still return text reply
    }
  }

  return {
    reply: reply.replace(/GENERATE:\s*.+?(\n|$)/gi, "").trim(),
    generatedSound,
  };
}
